heat_template_version: 2021-04-16

description: A simple template to deploy a single virtual machine with some outputs

resources:
  server01:
    type: OS::Nova::Server
    properties:
      key_name: default_key
      image: NeCTAR Ubuntu 22.04 LTS (Jammy) amd64
      flavor: t3.xsmall
      networks:
        - allocate_network: auto

outputs:
  instance_default:
    description: The IP address assigned to the server
    value: { get_attr: [server01, first_address ] }
  instance_show:
    description: Show many details about the server
    value: { get_attr: [server01, show] }
